package pl.grzegorz2047.productmanagement.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import pl.grzegorz2047.productmanagement.model.Opinion;
import pl.grzegorz2047.productmanagement.model.User;
import pl.grzegorz2047.productmanagement.repository.OpinionRepository;
import pl.grzegorz2047.productmanagement.repository.UserRepository;

import java.util.Date;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/opinions") // This means URL's start with /users (after Application path)
public class OpinionsController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OpinionRepository opinionRepositiory;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepositiory;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewOpinion(@RequestParam long userId, @RequestParam String opinionText) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User oneUser = userRepositiory.findOne(userId);
        if(null == oneUser) {
            return "user not found";
        }
        Opinion opinion = new Opinion(oneUser, opinionText, new Date());
        opinionRepositiory.save(opinion);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Opinion> getAllOpinions() {
        // This returns a JSON or XML with the users
        return opinionRepositiory.findAll();
    }
}