package pl.grzegorz2047.productmanagement.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import pl.grzegorz2047.productmanagement.model.*;
import pl.grzegorz2047.productmanagement.repository.*;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/opinions") // This means URL's start with /users (after Application path)
public class OpinionsController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OpinionRepository opinionRepositiory;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepositiory;

    @Autowired
    private ProductRepository productRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewOpinion(@RequestParam long userId, long productId, @RequestParam String opinionText, String pros, String cons, int score) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User oneUser = userRepositiory.findOne(userId);
        Product one = productRepository.findOne(productId);
        if (one != null) {
            ProductOpinion opinion = new ProductOpinion(oneUser, one, opinionText, new Date(), pros, cons, score);
            opinionRepositiory.save(opinion);
            return "Saved";
        } else {
            return "unknown eror";
        }
    }

    @GetMapping(path = "/all", produces = "application/json; charset=utf-8")
    public @ResponseBody
    Map<String, Iterable> getAllOpinions() {
        Map<String, Iterable> objects = new HashMap<>();
        objects.put("opinions", opinionRepositiory.findAll());
        return objects;
    }
}