package pl.grzegorz2047.productmanagement.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import pl.grzegorz2047.productmanagement.model.User;
import pl.grzegorz2047.productmanagement.repository.UserRepository;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /users (after Application path)
public class UsersController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if(name.equals("grzegorz")) {
            throw new IllegalArgumentException("");
        }
        User n = new User(name, password,new Date());
         userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody
    Map<String, Iterable> getAllUsers() {
        Map<String, Iterable> objects = new HashMap<>();
        objects.put("users", userRepository.findAll());
        return objects;
    }
    @ExceptionHandler({ IllegalArgumentException.class })
    public void handleException() {
        System.out.println("ERROR");
    }
}